theme: jekyll-theme-midnight
permalink: :year/:month/:day/:title
timezone: US/Pacific
exclude: ['sourceassets/', 'Gemfile', 'Gemfile.lock', 'LocalSite.url', 'ServeLocalSite.bat', 'UpdateGithubPages.bat', 'UpdateRubyGems.bat', 'TODO.txt', 'staticman.yml']
environment: live
